---
layout: rondrit
main: true
permalink: /ritten/2026-05-17-dwars-deur-drenthe/
title: "Dwars deur Drenthe"
date: 2026-05-17
afstand: 130
tags:
  - drenthe
  - lang
  - dagrit
organisatie: Chris & Erna
---
include::_attrs.adoc[opts=optional]
= {rit-titel}

== Dagindeling

De route is ongeveer 130 km lang en wordt alleen via gpx naar u toe verzonden.

Er zijn onderweg voldoende mogelijkheden voor een terrasje, of bezienswaardigheden of even de benen te strekken. Zie de folder, deze ontvang je samen in de week voor de rit met de GPX.

Wij wensen jullie een fijne dag.

Groetjes Chris en Erna

[cols="1,2,2,1,1", options="header"]
|===
| Tijd
| Locatie / Route
| Adres
| Duur
| Afstand

| 10:00 - 10:45
| Ontvangst bij https://maps.app.goo.gl/tkvZmCEAGGqF89GNA[*Bistro Aa*]
| Asserstraat 63, 9451 TA Rolde
| 45 min
|

|
2+| link:routes/[Route deel 1: Rolde - Nieuw Balinge]
|
| ~50 km

|
| Lunch bij https://maps.app.goo.gl/93QqAiXAuP5K7mwLA[*Koffie- en Theehuis Bi'j Oons*]
| Voornweg 1, 7938 RC Nieuw Balinge
|
|

|
2+| link:routes/[Route deel 2: Nieuw Balinge - Schoonloo]
|
| ~80 km

|
| Eindpunt bij https://maps.app.goo.gl/93QqAiXAuP5K7mwLA[*Eetcafé Hegeman*]
| Hoofdstraat 16, 9443 PA Schoonloo 
|
|

|===

*Totaal: ca. {rit-afstand}*

== Documenten

link:{site-baseurl}/assets/ritten/2026-05-17-dwars-deur-drenthe/docs/2026-05-17-weetjes-over-de-rit.pdf[↓ Weetjes over de rit (PDF)]
